# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ae63e9186c78ea8da4010532115964e6608551950669e37b590f06440aebada65418c11294c22dcedc673a781faebdc76081441306501be01b4511b1b302e84c

test:
  secret_key_base: 73fb22cf0fc0f69aff8f3504d07d930171654e930de6788f80c3c769ccb42e6e33a08c0c3536537bf082e7ed4bb1ba3422c327c5f4b2fbb05dae7651c9f80ec2

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
